apiVersion: v2
name: fabritor-web
description: Fabritor Web - 图片快速处理工具
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - fabritor
  - image-editor
  - canvas
  - fabricjs
home: https://github.com/freeb-vip/fabritor-web
sources:
  - https://github.com/freeb-vip/fabritor-web
maintainers:
  - name: freeb-vip
    url: https://github.com/freeb-vip
icon: https://raw.githubusercontent.com/freeb-vip/fabritor-web/main/public/favicon.ico
